{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-play-services",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6n3wvvyeubbytcxzxjyk33a5eq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.6.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-tasks",
          "version": {
            "requires": "16.0.1"
          },
          "excludes": [
            {
              "group": "com.android.support",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-play-services-1.6.0.jar",
          "url": "kotlinx-coroutines-play-services-1.6.0.jar",
          "size": 13053,
          "sha512": "40f8cbd0123a3d5f5430eb30779c024c60b17f3f3fae42faef241e555b152879ddc1c2af200496ec060eb185e629292f71f23abc98c61fcbc45f185be868f206",
          "sha256": "bf9ce78e5528180c7b3c7589bd211d126b1a8aaedef957682e8f06758644675b",
          "sha1": "bb0790ef5fc5bb686a61c47a7cc5ce7c5898ea3e",
          "md5": "8be3946114617a8f468cb2b81b4c9337"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.6.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-tasks",
          "version": {
            "requires": "16.0.1"
          },
          "excludes": [
            {
              "group": "com.android.support",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-play-services-1.6.0.jar",
          "url": "kotlinx-coroutines-play-services-1.6.0.jar",
          "size": 13053,
          "sha512": "40f8cbd0123a3d5f5430eb30779c024c60b17f3f3fae42faef241e555b152879ddc1c2af200496ec060eb185e629292f71f23abc98c61fcbc45f185be868f206",
          "sha256": "bf9ce78e5528180c7b3c7589bd211d126b1a8aaedef957682e8f06758644675b",
          "sha1": "bb0790ef5fc5bb686a61c47a7cc5ce7c5898ea3e",
          "md5": "8be3946114617a8f468cb2b81b4c9337"
        }
      ]
    }
  ]
}
